name = "dentalsys"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "dentalsys-db"
database_id = "a619cc4f-6427-48de-8665-2e3a6d019357"

[vars]
JWT_SECRET = "60d77cc1cdb4805020e6fd3c857bee47cb10ca4b5475323c576aeb57e5e16388"
APP_ENV = "production"
