// Prestaciones default del rubro odontología.
// Embebidas directamente (los Workers no hacen fetch de archivos en runtime).
export const PRESTACIONES_DEFAULT = [
  { codigo: '0101', nombre: 'Consulta y diagnóstico',            precio: 15000,  duracion_minutos: 30,  categoria: 'diagnostico' },
  { codigo: '0102', nombre: 'Radiografía periapical',            precio: 8000,   duracion_minutos: 15,  categoria: 'diagnostico' },
  { codigo: '0103', nombre: 'Radiografía panorámica',            precio: 25000,  duracion_minutos: 20,  categoria: 'diagnostico' },
  { codigo: '0201', nombre: 'Profilaxis y pulido',               precio: 20000,  duracion_minutos: 60,  categoria: 'preventiva' },
  { codigo: '0202', nombre: 'Aplicación de flúor',               precio: 8000,   duracion_minutos: 20,  categoria: 'preventiva' },
  { codigo: '0203', nombre: 'Sellante de fosa y fisura',         precio: 6000,   duracion_minutos: 20,  categoria: 'preventiva' },
  { codigo: '0301', nombre: 'Obturación resina (simple)',        precio: 22000,  duracion_minutos: 60,  categoria: 'restauraciones' },
  { codigo: '0302', nombre: 'Obturación resina (compuesta)',     precio: 30000,  duracion_minutos: 60,  categoria: 'restauraciones' },
  { codigo: '0303', nombre: 'Obturación amalgama',               precio: 18000,  duracion_minutos: 60,  categoria: 'restauraciones' },
  { codigo: '0304', nombre: 'Incrustación cerámica',             precio: 85000,  duracion_minutos: 90,  categoria: 'restauraciones' },
  { codigo: '0401', nombre: 'Endodoncia unirradicular',          precio: 55000,  duracion_minutos: 90,  categoria: 'endodoncia' },
  { codigo: '0402', nombre: 'Endodoncia birradicular',           precio: 70000,  duracion_minutos: 120, categoria: 'endodoncia' },
  { codigo: '0403', nombre: 'Endodoncia multirradicular',        precio: 90000,  duracion_minutos: 120, categoria: 'endodoncia' },
  { codigo: '0501', nombre: 'Extracción simple',                 precio: 18000,  duracion_minutos: 30,  categoria: 'cirugia' },
  { codigo: '0502', nombre: 'Extracción compleja',               precio: 30000,  duracion_minutos: 60,  categoria: 'cirugia' },
  { codigo: '0503', nombre: 'Extracción muela del juicio',       precio: 55000,  duracion_minutos: 90,  categoria: 'cirugia' },
  { codigo: '0601', nombre: 'Corona metal-porcelana',            precio: 120000, duracion_minutos: 90,  categoria: 'protesis' },
  { codigo: '0602', nombre: 'Corona zirconio/cerámica',          precio: 180000, duracion_minutos: 90,  categoria: 'protesis' },
  { codigo: '0603', nombre: 'Prótesis parcial removible',        precio: 250000, duracion_minutos: 60,  categoria: 'protesis' },
  { codigo: '0604', nombre: 'Prótesis total',                    precio: 350000, duracion_minutos: 60,  categoria: 'protesis' },
  { codigo: '0701', nombre: 'Implante dental (colocación)',      precio: 400000, duracion_minutos: 120, categoria: 'implantes' },
  { codigo: '0702', nombre: 'Corona sobre implante',             precio: 200000, duracion_minutos: 90,  categoria: 'implantes' },
  { codigo: '0801', nombre: 'Blanqueamiento (consultorio)',      precio: 80000,  duracion_minutos: 90,  categoria: 'estetica' },
  { codigo: '0802', nombre: 'Carilla de porcelana',              precio: 150000, duracion_minutos: 120, categoria: 'estetica' },
  { codigo: '0901', nombre: 'Consulta ortodoncia',               precio: 15000,  duracion_minutos: 30,  categoria: 'ortodoncia' },
  { codigo: '0902', nombre: 'Ortodoncia metálica (instalación)', precio: 120000, duracion_minutos: 90,  categoria: 'ortodoncia' },
  { codigo: '0903', nombre: 'Control mensual ortodoncia',        precio: 18000,  duracion_minutos: 30,  categoria: 'ortodoncia' },
  { codigo: '0904', nombre: 'Alineadores (Invisalign)',          precio: 600000, duracion_minutos: 60,  categoria: 'ortodoncia' },
  { codigo: '1001', nombre: 'Detartaje y raspado',               precio: 30000,  duracion_minutos: 60,  categoria: 'periodoncia' },
  { codigo: '1002', nombre: 'Cirugía periodontal',               precio: 80000,  duracion_minutos: 120, categoria: 'periodoncia' },
]
