// Prestaciones / servicios default.
// Embebidas directamente (los Workers no hacen fetch de archivos en runtime).
export const PRESTACIONES_DEFAULT = [
  { codigo: '0101', nombre: 'Consulta inicial / diagnóstico',     precio: 15000,  duracion_minutos: 30,  categoria: 'consultas' },
  { codigo: '0102', nombre: 'Consulta de seguimiento',            precio: 12000,  duracion_minutos: 20,  categoria: 'consultas' },
  { codigo: '0103', nombre: 'Consulta de urgencia',               precio: 20000,  duracion_minutos: 30,  categoria: 'consultas' },
  { codigo: '0104', nombre: 'Consulta telefónica / telemedicina', precio: 8000,   duracion_minutos: 15,  categoria: 'consultas' },
  { codigo: '0201', nombre: 'Radiografía simple',                 precio: 8000,   duracion_minutos: 15,  categoria: 'estudios' },
  { codigo: '0202', nombre: 'Ecografía',                          precio: 25000,  duracion_minutos: 30,  categoria: 'estudios' },
  { codigo: '0203', nombre: 'Electrocardiograma (ECG)',           precio: 15000,  duracion_minutos: 20,  categoria: 'estudios' },
  { codigo: '0204', nombre: 'Extracción de sangre / laboratorio', precio: 5000,   duracion_minutos: 10,  categoria: 'estudios' },
  { codigo: '0205', nombre: 'Espirometría',                       precio: 18000,  duracion_minutos: 30,  categoria: 'estudios' },
  { codigo: '0301', nombre: 'Curación / procedimiento menor',     precio: 12000,  duracion_minutos: 20,  categoria: 'procedimientos' },
  { codigo: '0302', nombre: 'Inyectable / aplicación',            precio: 8000,   duracion_minutos: 15,  categoria: 'procedimientos' },
  { codigo: '0303', nombre: 'Infiltración local',                 precio: 25000,  duracion_minutos: 20,  categoria: 'procedimientos' },
  { codigo: '0304', nombre: 'Sutura / desbridamiento',            precio: 20000,  duracion_minutos: 30,  categoria: 'procedimientos' },
  { codigo: '0305', nombre: 'Punción / drenaje',                  precio: 18000,  duracion_minutos: 20,  categoria: 'procedimientos' },
  { codigo: '0401', nombre: 'Control de presión arterial',        precio: 5000,   duracion_minutos: 10,  categoria: 'controles' },
  { codigo: '0402', nombre: 'Control de glucemia',                precio: 5000,   duracion_minutos: 10,  categoria: 'controles' },
  { codigo: '0403', nombre: 'Control de peso / antropometría',    precio: 5000,   duracion_minutos: 10,  categoria: 'controles' },
  { codigo: '0404', nombre: 'Control postoperatorio',             precio: 10000,  duracion_minutos: 20,  categoria: 'controles' },
  { codigo: '0501', nombre: 'Receta crónica / medicación habitual', precio: 5000, duracion_minutos: 10,  categoria: 'administrativo' },
  { codigo: '0502', nombre: 'Certificado médico',                 precio: 5000,   duracion_minutos: 10,  categoria: 'administrativo' },
  { codigo: '0503', nombre: 'Derivación a especialista',          precio: 5000,   duracion_minutos: 10,  categoria: 'administrativo' },
  { codigo: '0504', nombre: 'Historia clínica / informe',         precio: 8000,   duracion_minutos: 15,  categoria: 'administrativo' },
  { codigo: '0601', nombre: 'Sesión de kinesiología / fisioterapia', precio: 15000, duracion_minutos: 45, categoria: 'terapias' },
  { codigo: '0602', nombre: 'Sesión de psicología',               precio: 20000,  duracion_minutos: 50,  categoria: 'terapias' },
  { codigo: '0603', nombre: 'Sesión de nutrición',                precio: 18000,  duracion_minutos: 40,  categoria: 'terapias' },
  { codigo: '0604', nombre: 'Sesión de fonoaudiología',           precio: 15000,  duracion_minutos: 45,  categoria: 'terapias' },
  { codigo: '0701', nombre: 'Intervención / cirugía menor',       precio: 80000,  duracion_minutos: 60,  categoria: 'cirugia' },
  { codigo: '0702', nombre: 'Cirugía ambulatoria',                precio: 150000, duracion_minutos: 90,  categoria: 'cirugia' },
  { codigo: '0801', nombre: 'Plan de salud / programa',           precio: 50000,  duracion_minutos: 45,  categoria: 'preventiva' },
  { codigo: '0802', nombre: 'Vacunación',                         precio: 8000,   duracion_minutos: 10,  categoria: 'preventiva' },
]
